#!/usr/bin/python

import os
from optparse import OptionParser

parser = OptionParser()
parser.add_option("-f", "--file", dest="filename", help="write report to FILE", metavar="FILE")
(options, args) = parser.parse_args()

usage = "usage: %prog [options] arg1 arg2"
if 'options.filename' in locals():
	print options.filename
	os.system('echo "Test" > %s' % options.filename)

else :
	print usage


